### ISSUE TITLE
I can't sign up

### ISSUE THREAD

**Issue by Pigius** [asi-pwr/finansowanie#38]
When I'm trying to sign up into the portal - after submitting the form, the validation for a `full_name` input raises an error `Can't be blank`, even though I fulfilled it.

See in attachment.
<img width="1310" alt="screen shot 2018-05-12 at 10 34 22" src="https://user-images.githubusercontent.com/8863200/39955513-450ee23c-55d0-11e8-8bba-cbbf81587731.png">

**Comment by TeachMeHow** [comment]
Use website to create faculty and organisation, and then create user in console and also UserOrganisations association by connecting Organisation and User Id.
