### ISSUE TITLE
Missing padding

### ISSUE THREAD

**Issue by Pigius** [asi-pwr/finansowanie#39]
In application forms, it will be useful, to add some padding in the main container, to simply add spaces, to make it more appealing for users. Maybe `<div`> before the `yield` block?

<img width="1277" alt="screen shot 2018-05-12 at 10 38 49" src="https://user-images.githubusercontent.com/8863200/39955544-c747e0dc-55d0-11e8-9905-52c62941b602.png">

**Comment by Quintasan** [comment]
Fixed with  #41
