### ISSUE TITLE
Naprawić rejestrację

### ISSUE THREAD

**Issue by Quintasan** [asi-pwr/finansowanie#45]
Pan Adrian z działu Zespołu Bezpieczeństwa Informacji napisał do mnie że nie działa rejestracja. Musisz to zbadać i naprawić. Z tego co mi przemknęło zanim wyszedłeś to było to że któreś pole jest zawsze puste. Podejrzewam że to jest wina Strong Parameters w kontrolerze.

**Comment by Quintasan** [comment]
#38 ilustruje to dokładnie

**Comment by ostpczk** [comment]
[MR#47](https://github.com/asi-pwr/finansowanie/pull/47) plz

**Comment by Quintasan** [comment]
Closed by #47
